@startuml

skinparam linetype polyline
left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->


package ClientDomain{

    object StepVo{
        Sentence: string
    }

    object ResultVo{
        Content: string
    }

}





@enduml
