version: "3.9"
services:
  web:
    container_name: go-manager
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: $target
      args:
        GO_VERSION: 19.2
    image: go-manager:19.2-${target}
    ports:
      - "9090:9090"
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - .:/app
    tty: true

networks:
  default:
    name: pfm-network
    external: true