@startuml



rectangle "Client Server"  as SERVER <<$archimate/technology-device>> #Technology {
   archimate #Technology "      Client Program     " as clientServer <<technology-service>>
   archimate #Technology "    Control Program    " as controlProgram <<technology-service>>
}

clientServer <--> controlProgram : "cmd,responses"
@enduml