@startuml

skinparam linetype polyline
left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->



rectangle "Client Server"  as SERVERX <<$archimate/technology-device>> #Technology {
   archimate #Technology "      Client Program     " as clientProgram <<technology-service>>
   archimate #Technology "    Control Program    " as controlProgram <<technology-service>>
}


   rectangle "Hardware"  as SERVER <<$archimate/physical-equipment>> #Technology {
       archimate #Technology "   Engine    " as engine <<physical-equipment>>
       archimate #Technology "   H-Bridge Driver    " as hbridgedriver <<driver>>
   }

controlProgram <-> clientProgram : "cmd\nresponses        "
controlProgram <- engine : "\n                  sensors     "
controlProgram -> hbridgedriver : "\n\n\n\n\n\nsignal\n"
engine <-- hbridgedriver : "signal"
@enduml