version: "3.9"

services:
  envoy:
    build:
      context: .
      dockerfile: ./envoy/Dockerfile
    image: grpcweb/envoy
    ports:
      - "8080:8080"
      - "9901:9901"
  mysql:
    image: mysql:8.0
    ports:
      - "127.0.0.1:3306:3306"
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --general-log=1 --general-log-file=/tmp/mysql.log
    user: "1000:1000"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - pfm-db-data:/var/lib/mysql
volumes:
  pfm-db-data:
networks:
  default:
    name: pfm-network
    external: true