@startuml

start
if (hostValid) then (no)
  :throw InvalidHostError/
  stop
elseif (validPort) then (no)
  :throw InvalidPortError/
  stop
elseif (validCommunicationMode) then (no)
  :throw invalidCMode/
  stop
elseif (validExecutionMode) then (no)
  :throw invalidEMode/
  stop
elseif (validSteps) then (no)
  :throw invalidSteps/
  stop
else ()
  :CreateTask: Status = pending/
  :PersistTask/
  :trigger TaskCreatedEvent/
endif
:return new Task id/
stop
@enduml