@startuml
start

repeat
if (is param present) then (yes)
        if (is valid) then (no)
            :throw Invalid Param/
            stop
        else (yes)
        endif
else (no)
endif
repeat while(task parameters)
:UpdateTask/
:trigger TaskUpdatedEvent/
stop
@enduml