@startuml
start
if (host) then (yes)
    if (valid) then (no)
        :throw invalidHostError/
        stop
    else (yes)
    endif
else (no)
endif
if (Port) then (yes)
        if (valid) then (no)
            :throw invalidPortError/
            stop
        else (yes)
        endif
else (no)
endif
if (CommunicationMode) then (yes)
        if (valid) then (no)
            :throw invalidCommunicationModeError/
            stop
        else (yes)
        endif
else (no)
endif
if (ExecutionMode) then (yes)
        if (valid) then (no)
            :throw invalidExecutionModeError/
            stop
        else (yes)
        endif
else (no)
endif
if (steps) then (yes)
        if (valid) then (no)
            :throw invalidStepsError/
            stop
        else (yes)
        endif
else (no)
endif
if (status) then (yes)
        if (valid) then (no)
            :throw invalidStatusError/
            stop
        else (yes)
        endif
else (no)
endif
:UpdateTask/
:trigger TaskUpdatedEvent/
stop
@enduml